version: 2

builds:
  - binary: groo
    main: .
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.Version={{ .Version }}

archives:
  - name_template: '{{ .ProjectName }}_{{ if eq .Os "darwin" }}macOS{{ else }}{{ .Os }}{{ end }}_{{ .Arch }}'

release:
  prerelease: auto

homebrew_casks:
  - repository:
      owner: cyberwo1f
      name: homebrew-groo
    directory: Casks
    homepage: https://github.com/cyberwo1f/groo
    description: Opens the website for the current Git remote
    license: MIT
    binaries:
      - groo
